name: cve-scan

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/release.yml'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        id: build
        run: |
          IMAGE=deas/kind-wasmtime:${GITHUB_SHA}
          docker build -t ${IMAGE} .
          echo "::set-output name=image::$IMAGE"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
