name: test

on:
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/release.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests
        run: echo "make test"
      